### ISSUE TITLE
[enhancement] add shortcut for add page and …

### ISSUE THREAD

**Issue by wolfkingal2000** [mienaiyami/collection-extension-2.0#1]
Hi add shortcut  for add page
 and add updater page auto
  add manga or manhwa count chapter and update auto
 and make sync [yomikiru] can be good 
  can select all page in extension
I think these are all enhancements that should be added
and add notification for update manga and ... can be cool

**Comment by mienaiyami** [comment]
Shortcuts added, more will be added soon. 
Some features you mentioned are irrelevant so those won't be added.
