### ISSUE TITLE
Edge - Collections Function

### ISSUE THREAD

**Issue by rdas-21PZ** [mienaiyami/collection-extension-2.0#3]
Since an update in June or July 2024 I cannot sort when signed in to my MS account. I found out by accident I can sort collections when I am signed out of my MS Account? Sometimes, when I re-enter Collections, the sort function works only once. However, when still signed in and if I try a second sort, it fails. I find the collections function extremely useful, one of the best functions of the browser. Any advice would be appreciated.

**Comment by mienaiyami** [comment]
Can you provide more info or some screenshot?
Are you talking about "Microsoft Collection" that is on your browser by default? If so, this extension is not the microsoft's collection.
I'm not sure what sort you are talking about, but you can always rearrange by dragging collections.

**Comment by rdas-21PZ** [comment]
I am referring to MS Edge's browser. I thought I was dealing with their support people. Collections is a built in function of MS Edge. It was working fine until a few updates ago. Sorry for the confusion.

**Comment by mienaiyami** [comment]
No problem.
For me, Edge's collection started being really bad over a year ago and it was the reason I made this extension.
